### ISSUE TITLE
Add an about page

### ISSUE THREAD

**Issue by Wakeful-Cloud** [codeday/www-codecup#4]
Add a publically-viewable about page. It should include an auth button that users click to authenticate using the configured SSO provider instead of automatically redirecting to the SSO website since users may get confused or want to learn more without authenticating themselves.

**Comment by oohwooh** [comment]
this also reminds me that the CodeCup logo should probably be pulled from the CMS as well, this could be implemented pretty easily by importing the `Logo` component from topo, [as documented here](https://topo.codeday.org/?path=/docs/atom-logo--logo-with-text)

**Comment by oohwooh** [comment]
it's not like the codecup logo will change any time soon so no rush whatsoever on this
