### ISSUE TITLE
background particles get more intense through duration of event

### ISSUE THREAD

**Issue by oohwooh** [codeday/www-codecup#8]
It would be a nice touch if the background particles got more intense as the event goes on (or maybe just the longer someone spends on the page, that might be easier to implement) just like adding more particles idk that might be fun /shrug

**Comment by Wakeful-Cloud** [comment]
Unfortunately, this isn't possible to do without introducing noticeable jumps ([Reference](https://github.com/Wufe/react-particles-js/issues/58)).
