### ISSUE TITLE
Website is Gray Upon Loading

### ISSUE THREAD

**Issue by SchmitzAndrew** [codeday/www-codecup#9]
The website is grayed out until clicking somewhere besides the main challenges page.

**Comment by Wakeful-Cloud** [comment]
Yeah, I noticed that. This is due to the [challenge modal](https://github.com/codeday/www-codecup/blob/25eb07479c430cb16175f3192ee6d9b740498511/src/components/Challenge/Challenge.tsx#L21) bugging out.

**Comment by Wakeful-Cloud** [comment]
Related to [Chakra UI #3982](https://github.com/chakra-ui/chakra-ui/issues/3982#issuecomment-836630174)
